import { describe, expect, it } from "vitest";

import { renderReferencePage, symbolSlug } from "./reference-markdown.ts";
import type { ReferenceEntrypoint, ReferenceSymbol } from "./reference-model.ts";

function symbol(partial: Partial<ReferenceSymbol> & Pick<ReferenceSymbol, "name" | "kind">): ReferenceSymbol {
  return {
    typeParameters: [],
    parameters: [],
    throws: [],
    examples: [],
    see: [],
    members: [],
    ...partial,
  };
}

const entrypoint: ReferenceEntrypoint = {
  subpath: ".",
  module: "index",
  symbols: [
    symbol({
      name: "createAppError",
      kind: "function",
      signature: "export declare function createAppError(error: unknown): AppError;",
      doc: "Normalizes an unknown value into an {@link AppError}.",
      deprecated: "Use createError instead.",
      parameters: [{ name: "error", doc: "The raw value." }],
      returns: "A frozen error.",
      throws: ["When options is not an object.", "When maxDepth is negative."],
      since: "1.2.0",
    }),
    symbol({
      name: "AppError",
      kind: "interface",
      signature: "export interface AppError extends Error",
      doc: "Normalized error shape.",
      members: [
        {
          name: "messageKey",
          kind: "property",
          isOptional: true,
          isReadonly: true,
          isStatic: false,
          doc: "Translation key.",
          signature: "readonly messageKey?: string;",
          parameters: [],
        },
        {
          name: "toJSON",
          kind: "method",
          isOptional: false,
          isReadonly: false,
          isStatic: false,
          doc: "Serializes the error.",
          signature: "toJSON(space?: number): AppErrorJson;",
          parameters: [{ name: "space", doc: "Indentation passed through." }],
        },
      ],
    }),
    symbol({
      name: "ExternalThing",
      kind: "type-alias",
      signature: "export type ExternalThing = number;",
      doc: "See {@link https://mdn}.",
    }),
  ],
};

describe("renderReferencePage", () => {
  const page = renderReferencePage(entrypoint, {
    title: "/",
    heading: "@codenhub/error",
    sourceRoot: "packages/error/src",
    group: "Reference",
    prose: true,
  });

  it("emits closed frontmatter, a generated notice, and a single H1", () => {
    expect(page.startsWith("---\ntitle: /\ngroup: Reference\n---\n")).toBe(true);
    expect(page).toContain("<!-- Generated by `pnpm generate` from packages/error/src. Do not edit. -->");
    expect(page.match(/^# /gm)).toHaveLength(1);
    expect(page).toContain("# @codenhub/error");
  });

  it("groups symbols under kind headings in spec order", () => {
    const headings = [...page.matchAll(/^## (.+)$/gm)].map((match) => match[1]);
    expect(headings).toEqual(["Functions", "Interfaces", "Type aliases"]);
  });

  it("renders the signature, a deprecation blockquote, then prose and tag sections", () => {
    const section = page.slice(page.indexOf("### createAppError"), page.indexOf("### AppError"));
    expect(section).toContain("```ts\nexport declare function createAppError(error: unknown): AppError;\n```");
    expect(section).toContain("> **Deprecated.** Use createError instead.");
    expect(section).toContain("**Parameters**\n\n- `error` — The raw value.");
    expect(section).toContain("**Returns** — A frozen error.");
    expect(section).toContain("**Throws**\n\n- When options is not an object.\n- When maxDepth is negative.");
    expect(section).toContain("**Since** — 1.2.0");
    expect(section.indexOf("> **Deprecated.**")).toBeLessThan(section.indexOf("**Parameters**"));
  });

  it("emits description and since frontmatter when the entry module supplies them", () => {
    const enriched = renderReferencePage(entrypoint, {
      title: "/",
      heading: "@codenhub/error",
      sourceRoot: "packages/error/src",
      description: "Typed error normalization and result helpers.",
      since: "1.0.0",
      group: "Reference",
      prose: true,
    });
    expect(enriched).toContain(
      "---\ntitle: /\ndescription: Typed error normalization and result helpers.\nsince: 1.0.0\ngroup: Reference\n---\n",
    );
  });

  it("keeps the frontmatter version but drops the per-symbol Since line when prose is false", () => {
    const bare = renderReferencePage(entrypoint, {
      title: "/",
      heading: "@codenhub/error",
      sourceRoot: "packages/error/src",
      since: "1.0.0",
      order: 0,
      prose: false,
    });
    expect(bare).toContain("since: 1.0.0");
    expect(bare).not.toContain("**Since**");
  });

  it("renders a single-entry Throws or See also section as one inline line", () => {
    const single = renderReferencePage(
      {
        subpath: ".",
        module: "index",
        symbols: [
          symbol({
            name: "unwrap",
            kind: "function",
            signature: "export declare function unwrap<T>(result: Result<T>): T;",
            doc: "Returns the value or throws.",
            throws: ["When the result is an Err."],
            see: ["unwrapOr"],
          }),
        ],
      },
      { title: "/", heading: "@codenhub/error", sourceRoot: "packages/error/src", prose: true },
    );
    expect(single).toContain("**Throws** — When the result is an Err.");
    expect(single).not.toContain("**Throws**\n\n-");
    expect(single).toContain("**See also** — unwrapOr");
  });

  it("resolves an in-page {@link} to a heading anchor and leaves unknown targets as code", () => {
    expect(page).toContain("Normalizes an unknown value into an [AppError](#apperror).");
    expect(page).toContain("See {@link https://mdn}.".replace("{@link https://mdn}", "`https://mdn`"));
  });

  it("renders interface members with their own heading and signature block", () => {
    expect(page).toContain("#### messageKey\n\n```ts\nreadonly messageKey?: string;\n```\n\nTranslation key.");
  });

  it("renders a method member's documented parameters", () => {
    expect(page).toContain("#### toJSON");
    expect(page).toContain("Serializes the error.\n\n**Parameters**\n\n- `space` — Indentation passed through.");
  });

  it("omits prose when prose is false", () => {
    const bare = renderReferencePage(entrypoint, {
      title: "/",
      heading: "@codenhub/error",
      sourceRoot: "packages/error/src",
      order: 0,
      prose: false,
    });
    expect(bare).toContain("### createAppError\n\n```ts");
    expect(bare).not.toContain("**Parameters**");
    expect(bare).not.toContain("> **Deprecated.**");
    expect(bare).toContain("order: 0");
  });
});

describe("symbolSlug", () => {
  it("lower-cases a plain identifier and strips a leading sigil", () => {
    expect(symbolSlug("createAppError")).toBe("createapperror");
    expect(symbolSlug("$state")).toBe("state");
  });
});
