import { describe, expect, it } from "vitest";

import { renderReferencePage } from "./reference-markdown.ts";
import type { ReferenceEntrypoint, ReferenceSymbol } from "./reference-model.ts";

function symbol(partial: Partial<ReferenceSymbol> & Pick<ReferenceSymbol, "name" | "kind">): ReferenceSymbol {
  return {
    typeParameters: [],
    parameters: [],
    throws: [],
    examples: [],
    see: [],
    members: [],
    ...partial,
  };
}

const entrypoint: ReferenceEntrypoint = {
  subpath: ".",
  module: "index",
  symbols: [
    symbol({
      name: "createAppError",
      kind: "function",
      signature: "export declare function createAppError(error: unknown): AppError;",
      doc: "Normalizes an unknown value into an {@link AppError}.",
      deprecated: "Use createError instead.",
      parameters: [{ name: "error", doc: "The raw value." }],
      returns: "A frozen error.",
      throws: ["When options is not an object.", "When maxDepth is negative."],
    }),
    symbol({
      name: "AppError",
      kind: "interface",
      signature: "export interface AppError extends Error",
      doc: "Normalized error shape.",
      members: [
        {
          name: "messageKey",
          kind: "property",
          isOptional: true,
          isReadonly: true,
          isStatic: false,
          doc: "Translation key.",
          signature: "readonly messageKey?: string;",
          parameters: [],
        },
      ],
    }),
    symbol({
      name: "ExternalThing",
      kind: "type-alias",
      signature: "export type ExternalThing = number;",
      doc: "See {@link https://mdn}.",
    }),
  ],
};

describe("renderReferencePage", () => {
  const page = renderReferencePage(entrypoint, {
    title: "ErrorKit",
    sourceRoot: "packages/error/src",
    group: "Reference",
    prose: true,
  });

  it("emits closed frontmatter, a generated notice, and a single H1", () => {
    expect(page.startsWith("---\ntitle: ErrorKit\ngroup: Reference\n---\n")).toBe(true);
    expect(page).toContain("<!-- Generated by `pnpm generate` from packages/error/src. Do not edit. -->");
    expect(page.match(/^# /gm)).toHaveLength(1);
    expect(page).toContain("# ErrorKit");
  });

  it("groups symbols under kind headings in spec order", () => {
    const headings = [...page.matchAll(/^## (.+)$/gm)].map((match) => match[1]);
    expect(headings).toEqual(["Functions", "Interfaces", "Type aliases"]);
  });

  it("renders the signature, a deprecation blockquote, then prose and tag sections", () => {
    const section = page.slice(page.indexOf("### createAppError"), page.indexOf("### AppError"));
    expect(section).toContain("```ts\nexport declare function createAppError(error: unknown): AppError;\n```");
    expect(section).toContain("> **Deprecated.** Use createError instead.");
    expect(section).toContain("**Parameters**\n\n- `error` — The raw value.");
    expect(section).toContain("**Returns** — A frozen error.");
    expect(section).toContain("**Throws**\n\n- When options is not an object.\n- When maxDepth is negative.");
    expect(section.indexOf("> **Deprecated.**")).toBeLessThan(section.indexOf("**Parameters**"));
  });

  it("resolves an in-page {@link} to a heading anchor and leaves unknown targets as code", () => {
    expect(page).toContain("Normalizes an unknown value into an [AppError](#apperror).");
    expect(page).toContain("See {@link https://mdn}.".replace("{@link https://mdn}", "`https://mdn`"));
  });

  it("renders interface members with their own heading and signature block", () => {
    expect(page).toContain("#### messageKey\n\n```ts\nreadonly messageKey?: string;\n```\n\nTranslation key.");
  });

  it("omits prose when prose is false", () => {
    const bare = renderReferencePage(entrypoint, {
      title: "ErrorKit",
      sourceRoot: "packages/error/src",
      order: 0,
      prose: false,
    });
    expect(bare).toContain("### createAppError\n\n```ts");
    expect(bare).not.toContain("**Parameters**");
    expect(bare).not.toContain("> **Deprecated.**");
    expect(bare).toContain("order: 0");
  });
});
