import { roleSelectors, type StyleRegistry } from "./registry.ts";

const HEADER = `/* Generated by \`hub generate\` from registry.json. Do not edit.

   Membership is data and lives in the registry; what a role paints is code and
   lives beside this file in \`./<role>.css\`. This file is only the join between
   the two, which is why a component joins a role by editing one line of JSON. */`;

/** Slots every intent class and the shared reset declare, in a fixed order. */
const INTENT_SLOTS = ["color", "contrast", "hover", "strong", "subtle", "border"] as const;

/** Which half of the surface a generated membership file covers. */
export type MembershipScope = "class" | "native";

function block(selectors: readonly string[], body: readonly string[]): string {
  return `${selectors.join(",\n")} {\n${body.map((line) => `  ${line}`).join("\n")}\n}`;
}

function indent(text: string, by: string): string {
  return text.replace(/^(?=.)/gm, by);
}

/* The formatter collapses a `:where()` list that fits on one line and leaves a
   longer one expanded, so the generator has to make the same call. Otherwise
   every `hub generate` reports drift that the next `format:fix` undoes. */
const PRINT_WIDTH = 120;

function whereList(selectors: readonly string[], by: string): string {
  const inline = `${by}:where(${selectors.join(", ")}) {`;
  return inline.length <= PRINT_WIDTH
    ? inline
    : [`${by}:where(`, selectors.map((selector) => `${by}  ${selector}`).join(",\n"), `${by}) {`].join("\n");
}

/**
 * Renders the intent slots for one color family.
 *
 * Neutral is the family with two departures, both deliberate: its tinted surface
 * is the surface token rather than a text tint, and its line color defers to the
 * aesthetic's ink so an aesthetic can restate the neutral line without naming a
 * single component.
 * @param family Color family the intent maps onto.
 * @returns Declarations in slot order.
 */
export function intentSlots(family: string): string[] {
  const isNeutral = family === "text";
  const values: Record<(typeof INTENT_SLOTS)[number], string> = {
    border: isNeutral ? "var(--ui-ink, var(--color-border))" : `var(--color-${family})`,
    color: `var(--color-${family})`,
    contrast: `var(--color-${family}-contrast)`,
    hover: `var(--color-${family}-hover)`,
    strong: `var(--color-${family}-strong)`,
    subtle: isNeutral ? "var(--color-surface)" : `var(--color-${family}-subtle)`,
  };
  return INTENT_SLOTS.map((slot) => `--intent-${slot}: ${values[slot]};`);
}

/**
 * Renders `intent.css`: one class per intent, and nothing else.
 * @param registry Parsed registry.
 * @returns File contents.
 */
export function renderIntentCss(registry: StyleRegistry): string {
  const classes = Object.entries(registry.intents).map(([name, intent]) =>
    block([`.${name}`, ...(intent.aliases ?? []).map((alias) => `.${alias}`)], intentSlots(intent.family)),
  );

  return [
    HEADER,
    "",
    "/* An intent maps one color family onto six shared slots and does nothing else.",
    "   Supporting every intent therefore costs a component nothing, and adding one",
    "   costs six declarations.",
    "",
    "   Intent does not cascade. These classes set inheritable custom properties, but",
    "   every component redeclares the neutral defaults at its own root through the",
    "   reset in `roles/membership.css`, and a declaration on the element beats an",
    "   inherited one. A `.success` container cannot silently recolor a destructive",
    "   button nested inside it, while `.btn.success` still wins over the reset. */",
    "",
    classes.join("\n\n"),
    "",
  ].join("\n");
}

function scopedSelectors(component: StyleRegistry["components"][number], scope: MembershipScope): string[] {
  return scope === "class" ? [`.${component.class}`] : [...component.native];
}

function componentDefaults(
  registry: StyleRegistry,
  component: StyleRegistry["components"][number],
  selectors: readonly string[],
): string {
  const fill = component.default.fill === undefined ? undefined : registry.presentation.fill[component.default.fill];
  const edge = component.default.edge === undefined ? undefined : registry.presentation.edge[component.default.edge];
  const declarations = [
    ...(fill === undefined ? [] : [`--_d-fill: ${fill["ui-fill"]};`, `--_d-fg-on-fill: ${fill["ui-fg-on-fill"]};`]),
    ...(edge === undefined ? [] : [`--_d-border: ${edge["ui-border"]};`]),
    `--_d-elevation: ${component.default.elevation};`,
  ];
  const pair = [component.default.fill, component.default.edge].filter(Boolean).join(" ");
  return `/* ${component.class}: ${pair === "" ? "no presentation" : pair} */\n${block(selectors, declarations)}`;
}

function renderPreamble(registry: StyleRegistry, scope: MembershipScope): string {
  const imports = ['@reference "tailwindcss";', '@import "../theme.css";', '@import "./box.css";'].join("\n");

  if (scope === "native") {
    return [
      imports,
      "",
      HEADER,
      "",
      "/* The native half. A bare element joins a role the same way a class does,",
      "   which is what lets an aesthetic reach an unclassed `<button>`. It is loaded",
      "   only by `native.css`, so a consumer who did not opt into native element",
      "   styling never gets a bare element half-dressed: colored like an action but",
      "   carrying none of an action's geometry. */",
    ].join("\n");
  }

  const variants = Object.keys(registry.roles).map((role) => {
    const selectors = roleSelectors(registry, role).join(", ");
    return `@custom-variant role-${role} (&:is(${selectors}), & :is(${selectors}));`;
  });

  return [
    imports,
    "",
    HEADER,
    "",
    "/* The hover step is the one number the derived-hover formula spends, and the",
    "   registry owns it. */",
    ":root {",
    `  --hover-step: ${registry.presentation.hoverStep};`,
    "}",
    "",
    "/* Tier 2 of the aesthetic extension story. An aesthetic that must reach one kind",
    "   of component and not another applies a role variant rather than naming a",
    "   component, and the list it expands to is generated here, so an aesthetic never",
    "   falls behind when a component joins a role. */",
    variants.join("\n"),
  ].join("\n");
}

/**
 * Renders a role membership file: which selectors belong to which role, the
 * defaults each component rests at, and the shared intent reset.
 *
 * Classes and native elements are generated into separate files because the
 * package publishes them separately, and mixing them would leak the opt-in.
 * @param registry Parsed registry.
 * @param scope Whether to emit class selectors or native element selectors.
 * @returns File contents.
 */
export function renderMembershipCss(registry: StyleRegistry, scope: MembershipScope): string {
  const members = registry.components.filter((component) => scopedSelectors(component, scope).length > 0);
  const selectorsOf = (role: string): string[] =>
    members.filter((component) => component.role === role).flatMap((component) => scopedSelectors(component, scope));

  const everySelector = members.flatMap((component) => scopedSelectors(component, scope));
  const indicators = selectorsOf("indicator");

  const membership = Object.keys(registry.roles)
    .filter((role) => selectorsOf(role).length > 0)
    .map((role) => block(selectorsOf(role), [`@apply role-${role};`]));

  const indicatorReset =
    indicators.length === 0
      ? []
      : [
          "",
          "  /* An indicator takes the color it sits in rather than the shared neutral, so",
          "     a loader inside filled or colored content still matches it. It has to be",
          "     declared here at zero specificity: written inside the role's own block it",
          "     would carry 0-1-0 and, being later in the stylesheet, beat `.success` --",
          "     which silently makes every indicator ignore every intent class. */",
          whereList(indicators, "  "),
          "    --intent-color: currentColor;",
          "    --intent-border: currentColor;",
          "  }",
        ];

  return [
    renderPreamble(registry, scope),
    "",
    "@layer components {",
    "  /* Every selector in this file resolves the intent slots at its own root. Zero",
    "     specificity, so an intent class on the element wins over it while an",
    "     inherited value still loses -- any declaration on an element beats",
    "     inheritance regardless of specificity. That single rule is what lets every",
    "     component drop its own per-intent branches. */",
    whereList(everySelector, "  "),
    indent(intentSlots("text").join("\n"), "    "),
    "  }",
    ...indicatorReset,
    "",
    membership.map((rule) => indent(rule, "  ")).join("\n\n"),
    "",
    members
      .map((component) => componentDefaults(registry, component, scopedSelectors(component, scope)))
      .map((rule) => indent(rule, "  "))
      .join("\n\n"),
    "}",
    "",
  ].join("\n");
}
